-- =============================================
-- Karuna — Schema Migration v2
-- Run THIS if you already ran the original schema.
-- This only ADDS new columns and the new table.
-- =============================================

-- Fix existing constraint just in case
ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_current_site;

-- Add GPS columns to sites (for chatbot nearest-location routing)
ALTER TABLE sites ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 7);
ALTER TABLE sites ADD COLUMN IF NOT EXISTS longitude DECIMAL(10, 7);

-- Add nurse intake fields to patient_tags
ALTER TABLE patient_tags ADD COLUMN IF NOT EXISTS diagnosis TEXT;
ALTER TABLE patient_tags ADD COLUMN IF NOT EXISTS vitals TEXT;
ALTER TABLE patient_tags ADD COLUMN IF NOT EXISTS nurse_notes TEXT;

-- Add equipment_name to orders (doctors can request equipment, not just medicine)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS equipment_name TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ready_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP WITH TIME ZONE;

-- Add delivery workflow columns to donations
ALTER TABLE donations ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS self_delivery BOOLEAN DEFAULT false;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS delivery_address TEXT;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS delivery_status TEXT DEFAULT 'awaiting_pickup';
ALTER TABLE donations ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP WITH TIME ZONE;

-- Add volunteer profile fields to users (collected at site join, not registration)
ALTER TABLE users ADD COLUMN IF NOT EXISTS vehicle_availability TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS medical_equipment TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS medical_fitness BOOLEAN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS availability_duration TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS disaster_knowledge TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS doctors_needed INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS medical_specialty TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pharmacy_address TEXT;

-- Re-add constraint safely
ALTER TABLE users ADD CONSTRAINT fk_current_site
  FOREIGN KEY (current_site_id) REFERENCES sites(id) ON DELETE SET NULL;

-- Create the new Flags table (helper suggestions + complaints)
CREATE TABLE IF NOT EXISTS flags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id BIGINT REFERENCES sites(id) ON DELETE CASCADE,
  submitted_by UUID REFERENCES users(id),
  type TEXT NOT NULL,
  issue_type TEXT,
  title TEXT,
  description TEXT NOT NULL,
  severity TEXT DEFAULT 'Medium',
  status TEXT DEFAULT 'open',
  resolution_note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS on the new flags table
ALTER TABLE flags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated flags" ON flags FOR ALL USING (auth.role() = 'authenticated');

-- Create Volunteer Todos (if it doesn't exist yet)
CREATE TABLE IF NOT EXISTS volunteer_todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id BIGINT REFERENCES sites(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  patient_tag_id BIGINT REFERENCES patient_tags(id) ON DELETE SET NULL,
  task_description TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE volunteer_todos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated todos" ON volunteer_todos FOR ALL USING (auth.role() = 'authenticated');
